PustokSH/PustokSH/Areas/PustokAdmin/Controllers/TagController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PustokSH.Areas.PustokAdmin.ViewModels;
using PustokSH.DAL;
using PustokSH.Model;

namespace PustokSH.Areas.PustokAdmin.Controllers
{
    [Area("PustokAdmin")]
    public class TagController : Controller
    {
        private readonly AppDbContext _context;

        public TagController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int page=1)
        {
            int count=await _context.tags.CountAsync();
            List<Tag>tags= await _context.tags.Skip((page-1)*2).Take(2)
                .Include(t=>t.bookTags).ToListAsync();
            PaginatedVM<Tag> paginatedVM = new PaginatedVM<Tag>
            {
                items = tags,
                TotalPage = Math.Ceiling((double)count / 2),
                CurrentedPage=page
            };
            return View(paginatedVM);
        }
        public IActionResult Create()
        {
           return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Tag tag)
        {
            bool result= await _context.tags.AnyAsync(t=>t.Name==tag.Name);
            if (!ModelState.IsValid)
            {
                return View();
            }

            if (result)
            {
                ModelState.AddModelError("Name", "Eyni adli tag yarana bilmez");
                return View();
            }

            await _context.AddAsync(tag);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Update(int id)
        {
            if (id <= 0) return BadRequest();
            Tag tag = await _context.tags.FirstOrDefaultAsync(x => x.Id == id);
            if (tag == null) return NotFound();

            return View(tag);
        }
        [HttpPost]
        public async Task<IActionResult> Update(int id, Tag tag)
        {
            if (!ModelState.IsValid) return View();
            Tag existed = await _context.tags.FirstOrDefaultAsync(x => x.Id == id);
            if (existed == null) return NotFound();
            bool result = await _context.tags.AnyAsync(t => t.Name == tag.Name && t.Id != id);
            if (result)
            {
                ModelState.AddModelError("Name", "Bu adda tag artiq movcuddur");
                return View();

            }
            existed.Name = tag.Name;
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0) return BadRequest();
            Tag tag = await _context.tags.FirstOrDefaultAsync(x => x.Id == id);
            if (tag == null) return NotFound();
            _context.tags.Remove(tag);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        //public IActionResult Detail()
        //{
        //    return View();
        //}
        //[HttpPost]
        //public async Task<IActionResult> Detail(int id,Tag tag)
        //{
        //    if (!ModelState.IsValid) return View();
        //    Tag existed = await _context.tags.FirstOrDefaultAsync(x => x.Id == id);
        //    if (existed == null) return NotFound();
        //    bool result = await _context.tags.AnyAsync(a => a.Name == existed.Name && a.Id != id);
        //    if (result)
        //    {
        //        ModelState.AddModelError("FullName", "Bu adda author artiq movcuddur");
        //        return View();

        //    }
        //    existed.Name = tag.Name;
        //    await _context.SaveChangesAsync();

        //    return RedirectToAction(nameof(Index));
        //}

    }
}

PustokSH/PustokSH/Areas/PustokAdmin/Views/Tag/Create.cshtml
@model Tag

<div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Create tag</h4>

                <form class="forms-sample" method="post">
                    <div class="form-group">
                        <label for="exampleInputName1">Name</label>
                        <input asp-for="Name" class="form-control" placeholder="Name">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <a asp-action="index" class="btn btn-light">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>

PustokSH/PustokSH/Areas/PustokAdmin/Views/Tag/Detail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

PustokSH/PustokSH/Areas/PustokAdmin/Views/Tag/Index.cshtml
@model PaginatedVM<Tag>
@{
    int count = 0;
}
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Tags</h4>
                <a asp-action="Create"><button type="button" class="btn btn-success">Create</button></a>
                <div class="table-responsive pt-3">
                    <table class="table table-dark">
                        <thead>
                            <tr>
                                <th>
                                    No
                                </th>
                                <th>
                                    Name
                                </th>
                                <th>
                                    BooksTag
                                </th>
                                <th>
                                    Setting
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.items)
                            {
                                count++;

                                <tr>
                                    <td>
                                        @count
                                    </td>
                                    <td>
                                        @item.Name
                                    </td>
                                    <td>
                                        @item.bookTags.Count
                                    </td>
                                    <td>
                                        <a asp-action="update" asp-controller="Tag" asp-route-id="@item.Id" class="btn btn-warning btn-info"><i class="mdi mdi-grease-pencil"></i></a>
                                        <a asp-action="delete" asp-controller="Tag" asp-route-id="@item.Id" class="btn btn-danger btn-info"><i class="mdi mdi-delete-variant"></i></a>
                                        <a class="btn btn-primary"><i class="mdi mdi-arrow-top-right"></i></a>

                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item @(Model.CurrentedPage<=1?"disabled":"")">
                        <a class="page-link  " asp-controller="tag" asp-action="index" asp-route-page="@(Model.CurrentedPage-1)" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    @for (int i = 0; i < Model.TotalPage; i++)
                    {
                        <li class="page-item @(Model.CurrentedPage-1==i?"disabled":"")"><a class="page-link" asp-controller="tag" asp-action="index" asp-route-page="@(i+1)">@(i + 1)</a></li>
                    }
                    <li class="page-item @(Model.TotalPage<=Model.CurrentedPage?"disabled":"")">
                        <a class="page-link " asp-controller="tag" asp-action="index" asp-route-page="@(Model.CurrentedPage+1)" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>

PustokSH/PustokSH/Areas/PustokAdmin/Views/Tag/Update.cshtml
@model Tag

<div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Update tag</h4>

                <form class="forms-sample" method="post">
                    <div class="form-group">
                        <label for="exampleInputName1">Name</label>
                        <input asp-for="Name" class="form-control" placeholder="Name">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <a asp-action="index" class="btn btn-light">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>